# Gradle Properties
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false

# Source Options
use_modern_java_syntax = false

# Compilation Options
generate_sources_jar = true
generate_javadocs_jar = false

# Testing
enable_junit_testing = true
show_testing_output = false

# Mod Information
mod_version = INDEV
root_package = com.windanesz.menhir
mod_id = menhir
modid = menhir
mod_name = Menhir

# Mod Metadata (Optional)
mod_description = Menhir adds birthsigns to the game that grant unique abilities to the player
mod_url = https://www.curseforge.com/minecraft/mc-mods/menhir
mod_update_json = https://raw.githubusercontent.com/WinDanesz/Menhir/1.12.2/.forge/update.json
mod_authors = WinDanesz
mod_credits =
mod_logo_path =

# Mapping Properties
mapping_channel = stable
mapping_version = 39
use_dependency_at_files = true

# Run Configurations
minecraft_username = Developer
extra_jvm_args =
extra_tweak_classes =

# Maven Publishing
publish_to_maven = false
publish_to_local_maven = false
maven_name = ${mod_name}
maven_url =

# Publishing
release_type = release
publish_with_changelog = ${{ it.file('CHANGELOG.md').exists() }}

# Publishing to CurseForge
publish_to_curseforge = false
curseforge_project_id = 1335511
curseforge_debug = false

# Publishing to Modrinth
publish_to_modrinth = false
modrinth_project_id =
modrinth_sync_readme = false
modrinth_debug = false

# Modify Minecraft Sources
change_minecraft_sources = false

# Tags
use_tags = true
tag_class_name = ${root_package}.${mod_id}.Tags

# Access Transformers
use_access_transformer = false
access_transformer_locations = ${mod_id}_at.cfg

# Mixins
use_mixins = false
mixin_booter_version = 10.2
generate_mixins_json = false
mixin_configs = ${mod_id}
mixin_refmap = mixins.${mod_id}.refmap.json

# Coremods
is_coremod = false
coremod_includes_mod = true
coremod_plugin_class_name =

# AssetMover
use_asset_mover = false
asset_mover_version = 2.5

# Menhir Dependencies
wizardry_projectid=265642
wizardry_version=4.3.15
wizardry_fileid=6950392
baubles_projectid=227083
baubles_version=1.5.2
baubles_fileid=2518667
jei_projectid=238222
jei_version=4.16.1.302
artemislib_projectid=313590
artemislib_version=1.0.6
artemislib_fileid=2741812
antiqueatlas_projectid=227795
antiqueatlas_fileid=2823030
mixinbooter_projectid=419286
mixinbooter_fileid=4828995
wizardry_utils_version=1.3.0
wizardryutils_projectid=608287
wizardryutils_fileid=7158305